### PR TITLE
shorten loop

### PR DESCRIPTION
**Pull request by MaxOstrowski**
early break for negative cycle

### CODE REVIEW

**Comment by rkaminsk** [comment]
On first glance it looks right but I have not had a closer look at the code in a long time. Does the shortcut make a difference?

**Comment by MaxOstrowski** [comment]
On some instances it makes it faster (like 1/10 speed).
But I only tested my limited testset which may not be representative.

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4443667/results.zip)

On our bigger non-representative test set we get the following results:
It seams not for free (1 extra check in an inner loop), its positive impact is also negligible.
Leave it out ?

**Comment by rkaminsk** [comment]
> [results.zip](https://github.com/potassco/clingoDL/files/4443667/results.zip)
> 
> On our bigger non-representative test set we get the following results:
> It seams not for free (1 extra check in an inner loop), its positive impact is also negligible.
> Leave it out ?

It looks like it only has an effect on the train scheduling examples. For all other instances the conflict/choice counts when there are no timeouts are the same. I don't mind having it. The overhead will always be negligible.

**Comment by MaxOstrowski** [comment]
I expected the choice/conflicts to be exactly the same without propagation.
On instances/train/05_V1.02_FWA_with_obstruction.lp this is not the case, do you have an idea why ?

**Comment by rkaminsk** [comment]
Closing this. It seems useless.

**Pull request closed without merging**
